app:
  log_level: DEBUG
  preload_metadata: True

postgres_db:
  host: 192.168.222.204:5432
  db_name: chu-bordeaux
  user: ghpsj
  pwd: starclay2018

sparql_db:
  host: 'http://192.168.222.218:8888/sparql-endpoint'
  use_metadata: True